<?xml version="1.0"?>
<!--
Copyright (c) 2019, I3D Robotics Ltd.
-->

<robot xmlns:xacro="http://ros.org/wiki/xacro">
    <xacro:macro name="i3dr_phobos_nuclear" params="camera_name:=phobos_nuclear en_mesh:=false">
        <xacro:property name="height" value="0.045"/>
        <xacro:property name="width" value="0.305"/>
        <xacro:property name="length" value="0.13"/>
        <xacro:property name="mesh_file" value="package://i3dr_phobos_nuclear/mesh/phobos_nuclear.stl"/>
        <xacro:property name="mesh_offset_xyz" value="0 0 0"/>
        <xacro:property name="mesh_offset_rpy" value="0 0 ${-pi/2}"/>
        <xacro:property name="box_offset_xyz" value="${(length/2)-(height/2)} 0 0"/>
        <xacro:property name="box_offset_rpy" value="0 0 0"/>

        <xacro:property name="toe_in_l" value="0"/>
        <xacro:property name="toe_in_r" value="0"/>

        <link name="${camera_name}_cameraLeft_optical" />
        <link name="${camera_name}_cameraRight_optical" />
        <link name="${camera_name}_cameraLeft" />
        <link name="${camera_name}_cameraRight" />

        <link name="${camera_name}_depth_optical_frame" />

        <link name="${camera_name}_base_link" >
            <visual>
                <xacro:if value="${(en_mesh == 'true')}">
                    <origin xyz="${mesh_offset_xyz}" rpy="${mesh_offset_rpy}"/>
                </xacro:if>
                <xacro:if value="${(en_mesh == 'false')}">
                    <origin xyz="${box_offset_xyz}" rpy="${box_offset_rpy}"/>
                </xacro:if>
                <geometry>
                    <xacro:if value="${(en_mesh == 'true')}">
                        <mesh filename="${mesh_file}"/>
                    </xacro:if>
                    <xacro:if value="${(en_mesh == 'false')}">
                        <box size="${length} ${width} ${height}"/>
                    </xacro:if>
                </geometry>
                <xacro:if value="${(en_mesh == 'false')}">
                    <material name="${camera_name}_camera_colour">
                        <color rgba="0.1 0.1 0.1 1"/>
                    </material>
                </xacro:if>
            </visual>
        </link>

        <link name="${camera_name}_mount_point_1"/>
        <link name="${camera_name}_mount_point_2"/>
        <link name="${camera_name}_mount_point_3"/>
        <link name="${camera_name}_mount_point_4"/>

        <link name="${camera_name}_center"/>

        <joint name="${camera_name}_right_camera_joint" type="fixed">
            <parent link="${camera_name}_center"/>
            <child link="${camera_name}_cameraRight"/>
            <origin xyz="0 ${-0.125} 0" rpy="0 0 0" />
        </joint>

        <joint name="${camera_name}_left_camera_joint" type="fixed">
            <parent link="${camera_name}_center"/>
            <child link="${camera_name}_cameraLeft"/>
            <origin xyz="0 ${0.125} 0" rpy="0 0 0" />
        </joint>

        <joint name="${camera_name}_left_optical_joint" type="fixed">
            <parent link="${camera_name}_cameraLeft"/>
            <child link="${camera_name}_cameraLeft_optical"/>
            <!-- Correct for the optical frame orientation -->
            <origin xyz="0 0 0" rpy="${-pi/2} 0 ${(-pi/2)-(toe_in_l * (pi/180))}" />
        </joint>

        <joint name="${camera_name}_right_optical_joint" type="fixed">
            <parent link="${camera_name}_cameraRight"/>
            <child link="${camera_name}_cameraRight_optical"/>
            <!-- Correct for the optical frame orientation -->
            <origin xyz="0 0 0" rpy="${-pi/2} 0 ${(-pi/2)+(toe_in_r * (pi/180))}" />
        </joint>

        <joint name="${camera_name}_depth_optical_joint" type="fixed">
            <parent link="${camera_name}_cameraRight"/>
            <child link="${camera_name}_depth_optical_frame"/>
            <origin xyz="0 0 0" rpy="${-pi/2} 0 ${(-pi/2)}" />
        </joint>

        <joint name="${camera_name}_mount_center_joint" type="fixed">
            <parent link="${camera_name}_base_link"/>
            <child link="${camera_name}_center"/>
            <origin xyz="0.017675 0 0.167" rpy="${pi/2} 0 ${-pi/2}" />
        </joint>

        <joint name="${camera_name}_mount_point_1_joint" type="fixed">
            <parent link="${camera_name}_base_link"/>
            <child link="${camera_name}_mount_point_1"/>
            <origin xyz="0.0176775 0.0176775 0" rpy="0 0 0" />
        </joint>
        <joint name="${camera_name}_mount_point_2_joint" type="fixed">
            <parent link="${camera_name}_base_link"/>
            <child link="${camera_name}_mount_point_2"/>
            <origin xyz="-0.0176775 0.0176775 0" rpy="0 0 0" />
        </joint>
        <joint name="${camera_name}_mount_point_3_joint" type="fixed">
            <parent link="${camera_name}_base_link"/>
            <child link="${camera_name}_mount_point_3"/>
            <origin xyz="0.0176775 -0.0176775 0" rpy="0 0 0" />
        </joint>
        <joint name="${camera_name}_mount_point_4_joint" type="fixed">
            <parent link="${camera_name}_base_link"/>
            <child link="${camera_name}_mount_point_4"/>
            <origin xyz="-0.0176775 -0.0176775 0" rpy="0 0 0" />
        </joint>

        <gazebo reference="${camera_name}_cameraLeft">
            <sensor type="multicamera" name="${camera_name}_camera">
            <update_rate>0.5</update_rate> <!-- reality 60fps on USB3-->
            <camera name="left">
                <horizontal_fov>1.04</horizontal_fov>
                <image>
                    <width>752</width>
                    <height>480</height>
                    <format>L8</format>
                </image>
                <clip>
                    <near>0.02</near>
                    <far>300</far>
                </clip>
                <noise>
                    <type>gaussian</type>
                    <mean>0.0</mean>
                    <stddev>0.007</stddev>
                </noise>
            </camera>
            <camera name="right">
                <pose>0 -0.07 0 0 0 0</pose>
                <horizontal_fov>1.3962634</horizontal_fov>
                <image>
                    <width>752</width>
                    <height>480</height>
                    <format>L8</format>
                </image>
                <clip>
                    <near>0.02</near>
                    <far>300</far>
                </clip>
                <noise>
                    <type>gaussian</type>
                    <mean>0.0</mean>
                    <stddev>0.007</stddev>
                </noise>
            </camera>
            <plugin name="${camera_name}_camera_controller" filename="libgazebo_ros_multicamera.so">
                <alwaysOn>true</alwaysOn>
                <updateRate>0.5</updateRate>
                <cameraName>${camera_name}</cameraName>
                <imageTopicName>${camera_name}/image_raw</imageTopicName>
                <cameraInfoTopicName>${camera_name}/camera_info</cameraInfoTopicName>
                <frameName>${camera_name}_cameraLeft_optical</frameName>
                <hackBaseline>0.07</hackBaseline>
                <distortionK1>0.0</distortionK1>
                <distortionK2>0.0</distortionK2>
                <distortionK3>0.0</distortionK3>
                <distortionT1>0.0</distortionT1>
                <distortionT2>0.0</distortionT2>
            </plugin>
            </sensor>
        </gazebo>

        <gazebo reference="${camera_name}_depth_camera">
            <sensor type="depth" name="${camera_name}_depth_camera">
            <update_rate>0.5</update_rate>
            <camera>
                <horizontal_fov>${62.8 * pi/180.0}</horizontal_fov>
                <image>
                <format>R8G8B8</format>
                <width>640</width>
                <height>480</height>
                </image>
                <clip>
                <near>0.05</near>
                <far>12</far>
                </clip>
            </camera>
            <plugin name="${camera_name}_depth_camera_controller" filename="libgazebo_ros_openni_kinect.so">
                <alwaysOn>true</alwaysOn>
                <updateRate>0.5</updateRate>
                <imageTopicName>${camera_name}/image_raw</imageTopicName>
                <cameraInfoTopicName>${camera_name}/camera_info</cameraInfoTopicName>
                <depthImageTopicName>${camera_name}/depth/image_raw</depthImageTopicName>
                <depthImageCameraInfoTopicName>${camera_name}/depth/camera_info</depthImageCameraInfoTopicName>
                <pointCloudTopicName>${camera_name}/depth/points</pointCloudTopicName>
                <frameName>${camera_name}_depth_optical_frame</frameName>
                <distortion_k1>0.0</distortion_k1>
                <distortion_k2>0.0</distortion_k2>
                <distortion_k3>0.0</distortion_k3>
                <distortion_t1>0.0</distortion_t1>
                <distortion_t2>0.0</distortion_t2>
            </plugin>
            </sensor>
    </gazebo>
    </xacro:macro>
</robot>